/*
Author:Daniel Cooney
Date:9/10/17
Lastest Edit: 18/10/17
*/

CC=g++
CFLAGS= -std=c++11 -pthread
FILES= signal.cpp Semaphore.cpp
OUT_EXE=signal

build: $(FILES)
	$(CC) -o $(OUT_EXE) $(FILES) $(CFLAGS)


